language: ruby
cache: bundler
rvm:
- 1.9.3-p484
- 2.0.0-p353
- 2.1.0
- 2.1.2
notifications:
  email: false
  slack:
    secure: Qc7qj/J8Vy+/x89IZ2U2NpdHVmllak+d/Sd6czLgeGEWOvnxz0aNrxu1skp1qWkNtz3BbF5hPVHhGs3J4yt2YQoeB5jOr2bvEmFeIpMnXtx4ACtonlLSTA7e2Ol33paMIarTwh4ZPAyVnw54c/Mn5856rqGCPYgPVXHqsjXSw8s=
